### ISSUE TITLE
DB Error

### ISSUE THREAD

**Issue by gihanrcg** [ChrisLFieldsII/mern-azure-example#2]
When connecting to the DB there is an error saying that the DB name should be a String even though it already is

**Comment by gihanrcg** [comment]
```
D:\Private\VolunteerProj\node_modules\mongodb\lib\operations\db_ops.js:549
    throw MongoError.create({ message: 'database name must be a string', driver: true });
    ^

MongoError: database name must be a string
    at Function.create (D:\Private\VolunteerProj\node_modules\mongodb\lib\core\error.js:44:12)
    at validateDatabaseName (D:\Private\VolunteerProj\node_modules\mongodb\lib\operations\db_ops.js:549:22)
    at new Db (D:\Private\VolunteerProj\node_modules\mongodb\lib\db.js:190:3)
    at MongoClient.db (D:\Private\VolunteerProj\node_modules\mongodb\lib\mongo_client.js:275:14)
    at D:\Private\VolunteerProj\node_modules\mongoose\lib\connection.js:638:62
    at result (D:\Private\VolunteerProj\node_modules\mongodb\lib\operations\execute_operation.js:75:17)
    at executeCallback (D:\Private\VolunteerProj\node_modules\mongodb\lib\operations\execute_operation.js:68:9)
    at err (D:\Private\VolunteerProj\node_modules\mongodb\lib\operations\connect.js:193:7)
    at connectCallback (D:\Private\VolunteerProj\node_modules\mongodb\lib\operations\connect.js:340:5)
    at topology.connect (D:\Private\VolunteerProj\node_modules\mongodb\lib\operations\connect.js:472:7)
    at Server.connectHandler (D:\Private\VolunteerProj\node_modules\mongodb\lib\core\sdam\topology.js:259:45)
    at Object.onceWrapper (events.js:276:13)
    at Server.emit (events.js:193:15)
    at Pool.<anonymous> (D:\Private\VolunteerProj\node_modules\mongodb\lib\core\sdam\server.js:470:12)
    at Pool.emit (events.js:188:13)
    at connect (D:\Private\VolunteerProj\node_modules\mongodb\lib\core\connection\pool.js:624:10)
```
